In [1]:
import numpy as np
import pandas as pd
import bokeh as bk
from bokeh.sampledata.autompg import autompg as df
df['Company']=df.name
df.dropna(inplace = True) 
# To remove the errors
df['Company']=df["Company"].str.split(" ", n = 1, expand = True)
gk=df.groupby('Company')
gk.first()

,mpg,cyl,displ,hp,weight,accel,yr,origin,name
Company,,,,,,,,,
amc,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
audi,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls
bmw,26.0,4,121.0,113,2234,12.5,70,2,bmw 2002
buick,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
cadillac,16.5,8,350.0,180,4380,12.1,76,1,cadillac seville
capri,25.0,4,140.0,92,2572,14.9,76,1,capri ii
chevroelt,16.0,6,250.0,105,3897,18.5,75,1,chevroelt chevelle malibu
chevrolet,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
chevy,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
chrysler,13.0,8,400.0,190,4422,12.5,72,1,chrysler newport royal
datsun,27.0,4,97.0,88,2130,14.5,70,3,datsun pl510
dodge,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se
fiat,30.0,4,88.0,76,2065,14.5,71,2,fiat 124b
ford,17.0,8,302.0,140,3449,10.5,70,1,ford torino
hi,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
honda,24.0,4,120.0,97,2489,15.0,74,3,honda civic
maxda,18.0,3,70.0,90,2124,13.5,73,3,maxda rx3
mazda,19.0,3,70.0,97,2330,13.5,72,3,mazda rx2 coupe
mercedes,25.4,5,183.0,77,3530,20.1,79,2,mercedes benz 300d
mercedes-benz,16.5,6,168.0,120,3820,16.7,76,2,mercedes-benz 280s
mercury,23.0,4,122.0,86,2220,14.0,71,1,mercury capri 2000
nissan,36.0,4,120.0,88,2160,14.5,82,3,nissan stanza xe
oldsmobile,12.0,8,350.0,160,4456,13.5,72,1,oldsmobile delta 88 royale
opel,28.0,4,116.0,90,2123,14.0,71,2,opel 1900
peugeot,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504
plymouth,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
pontiac,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
renault,26.0,4,96.0,69,2189,18.0,72,2,renault 12 (sw)
saab,25.0,4,104.0,95,2375,17.5,70,2,saab 99e
subaru,26.0,4,108.0,93,2391,15.5,74,3,subaru
toyota,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii
toyouta,23.0,4,120.0,97,2506,14.5,72,3,toyouta corona mark ii (sw)
triumph,35.0,4,122.0,88,2500,15.1,80,2,triumph tr7 coupe
vokswagen,29.8,4,89.0,62,1845,15.3,80,2,vokswagen rabbit
volkswagen,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
volvo,18.0,4,121.0,112,2933,14.5,72,2,volvo 145e (sw)
vw,29.0,4,90.0,70,1937,14.2,76,2,vw rabbit